// <auto-generated />
using System;
using Estoque.Infra.Database.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estoque.Infra.Database.Migrations
{
    [DbContext(typeof(AppDbContextEstoque))]
    [Migration("20260318032326_atualizacaoDatas")]
    partial class atualizacaoDatas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Estoque.Dominio.Modelos.MovimentoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<Guid?>("PedidoExternoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PEDIDO_EXTERNO_ID");

                    b.Property<Guid>("ProdutoEstoqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoEstoqueId");

                    b.ToTable("movimento_estoque", (string)null);
                });

            modelBuilder.Entity("ProdutoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int")
                        .HasColumnName("ESTOQUE_MINIMO");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantidadeDisponivel")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE_DISPONIVEL");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ULTIMA_ATUALIZACAO");

                    b.HasKey("Id");

                    b.ToTable("produto_estoque", (string)null);
                });

            modelBuilder.Entity("Estoque.Dominio.Modelos.MovimentoEstoque", b =>
                {
                    b.HasOne("ProdutoEstoque", "ProdutoEstoque")
                        .WithMany()
                        .HasForeignKey("ProdutoEstoqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProdutoEstoque");
                });
#pragma warning restore 612, 618
        }
    }
}
